---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
    space: $KUBE_NAMESPACE
    track: stable
spec:
  selector:
    matchLabels:
      app: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
      name: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
      track: stable
  template:
    metadata:
      labels:
        name: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
        app: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
        track: stable
        space: $KUBE_NAMESPACE
      annotations:
        build_id: "$CI_JOB_ID"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        command: ["/bin/herokuish"]
        args: ["procfile", "start", "{{PREFIX}}"]
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: $PORT
        resources:
          limits:
            cpu: "${{PREFIX}}_LIMIT_CPU"
            memory: "${{PREFIX}}_LIMIT_MEMORY"
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - ${{PREFIX}}_LIVENESS_PROBE
        env:
          {{SECRETS}}
      imagePullSecrets:
        - name: gitlab-registry